
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  1 2020 17:51:47 +07 (Aug  1 2020 10:51:47 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(clk, rst_n, flick, LED);
  input clk, rst_n, flick;
  output [15:0] LED;
  wire clk, rst_n, flick;
  wire [15:0] LED;
  wire [3:0] next_index;
  wire [3:0] index;
  wire [15:0] next_LED;
  wire [1:0] next_state;
  wire [1:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, n_0, n_1;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_118;
  wire n_122, n_126, n_130, n_134, n_138, n_142, n_146, n_148;
  wire n_150, n_152, n_154, n_158, n_162, n_166, n_170, n_174;
  wire n_177, n_204, n_213, n_226, n_239;
  DFFSRHQX1 \index_reg[2] (.RN (n_71), .SN (n_83), .CK (clk), .D
       (next_index[2]), .Q (index[2]));
  DFFSRHQX1 \index_reg[0] (.RN (n_76), .SN (n_97), .CK (clk), .D
       (next_index[0]), .Q (index[0]));
  DFFSRHQX1 \index_reg[1] (.RN (n_77), .SN (n_107), .CK (clk), .D
       (next_index[1]), .Q (index[1]));
  TLATNXL \next_index_reg[2] (.GN (n_114), .D (n_113), .Q
       (next_index[2]), .QN (UNCONNECTED));
  DFFSRHQX2 \LED_reg[2] (.RN (n_31), .SN (n_61), .CK (clk), .D
       (next_LED[2]), .Q (LED[2]));
  DFFSRHQX2 \LED_reg[13] (.RN (n_34), .SN (n_59), .CK (clk), .D
       (next_LED[13]), .Q (LED[13]));
  DFFSRHQX2 \LED_reg[14] (.RN (n_45), .SN (n_63), .CK (clk), .D
       (next_LED[14]), .Q (LED[14]));
  DFFSRHQX2 \LED_reg[4] (.RN (n_30), .SN (n_65), .CK (clk), .D
       (next_LED[4]), .Q (LED[4]));
  DFFSRHQX2 \LED_reg[3] (.RN (n_46), .SN (n_60), .CK (clk), .D
       (next_LED[3]), .Q (LED[3]));
  DFFSRHQX2 \LED_reg[5] (.RN (n_36), .SN (n_66), .CK (clk), .D
       (next_LED[5]), .Q (LED[5]));
  DFFSRHQX2 \LED_reg[6] (.RN (n_35), .SN (n_47), .CK (clk), .D
       (next_LED[6]), .Q (LED[6]));
  DFFSRHQX2 \LED_reg[1] (.RN (n_42), .SN (n_54), .CK (clk), .D
       (next_LED[1]), .Q (LED[1]));
  DFFSRHQX2 \LED_reg[0] (.RN (n_40), .SN (n_55), .CK (clk), .D
       (next_LED[0]), .Q (LED[0]));
  DFFSRHQX2 \LED_reg[11] (.RN (n_38), .SN (n_48), .CK (clk), .D
       (next_LED[11]), .Q (LED[11]));
  DFFSRHQX2 \LED_reg[12] (.RN (n_32), .SN (n_50), .CK (clk), .D
       (next_LED[12]), .Q (LED[12]));
  DFFSRHQX2 \LED_reg[10] (.RN (n_44), .SN (n_49), .CK (clk), .D
       (next_LED[10]), .Q (LED[10]));
  DFFSRHQX2 \LED_reg[7] (.RN (n_43), .SN (n_53), .CK (clk), .D
       (next_LED[7]), .Q (LED[7]));
  DFFSRHQX2 \LED_reg[8] (.RN (n_33), .SN (n_52), .CK (clk), .D
       (next_LED[8]), .Q (LED[8]));
  DFFSRHQX2 \LED_reg[9] (.RN (n_41), .SN (n_51), .CK (clk), .D
       (next_LED[9]), .Q (LED[9]));
  TLATNXL \next_index_reg[1] (.GN (n_114), .D (n_112), .Q
       (next_index[1]), .QN (UNCONNECTED0));
  TLATNXL \next_index_reg[0] (.GN (n_114), .D (n_110), .Q
       (next_index[0]), .QN (UNCONNECTED1));
  TLATNXL \next_LED_reg[1] (.GN (n_114), .D (n_93), .Q (next_LED[1]),
       .QN (UNCONNECTED2));
  TLATNXL \next_LED_reg[3] (.GN (n_114), .D (n_91), .Q (next_LED[3]),
       .QN (UNCONNECTED3));
  TLATNXL \next_LED_reg[2] (.GN (n_114), .D (n_92), .Q (next_LED[2]),
       .QN (UNCONNECTED4));
  TLATNXL \next_LED_reg[6] (.GN (n_114), .D (n_108), .Q (next_LED[6]),
       .QN (UNCONNECTED5));
  TLATNXL \next_LED_reg[4] (.GN (n_114), .D (n_95), .Q (next_LED[4]),
       .QN (UNCONNECTED6));
  TLATNXL \next_LED_reg[5] (.GN (n_114), .D (n_94), .Q (next_LED[5]),
       .QN (UNCONNECTED7));
  TLATNXL \next_LED_reg[12] (.GN (n_114), .D (n_105), .Q
       (next_LED[12]), .QN (UNCONNECTED8));
  TLATNXL \next_LED_reg[9] (.GN (n_114), .D (n_86), .Q (next_LED[9]),
       .QN (UNCONNECTED9));
  TLATNXL \next_LED_reg[7] (.GN (n_114), .D (n_88), .Q (next_LED[7]),
       .QN (UNCONNECTED10));
  TLATNXL \next_LED_reg[11] (.GN (n_114), .D (n_89), .Q (next_LED[11]),
       .QN (UNCONNECTED11));
  TLATNXL \next_LED_reg[10] (.GN (n_114), .D (n_85), .Q (next_LED[10]),
       .QN (UNCONNECTED12));
  TLATNXL \next_LED_reg[8] (.GN (n_114), .D (n_87), .Q (next_LED[8]),
       .QN (UNCONNECTED13));
  TLATNXL \next_LED_reg[13] (.GN (n_114), .D (n_102), .Q
       (next_LED[13]), .QN (UNCONNECTED14));
  TLATNXL \next_LED_reg[14] (.GN (n_114), .D (n_101), .Q
       (next_LED[14]), .QN (UNCONNECTED15));
  TLATNXL \next_state_reg[1] (.GN (n_114), .D (n_99), .Q
       (next_state[1]), .QN (UNCONNECTED16));
  TLATNXL \next_LED_reg[0] (.GN (n_114), .D (n_90), .Q (next_LED[0]),
       .QN (UNCONNECTED17));
  OAI2BB1X1 g5751__2398(.A0N (index[2]), .A1N (n_111), .B0 (n_98), .Y
       (n_113));
  TLATNXL \next_index_reg[3] (.GN (n_114), .D (n_100), .Q
       (next_index[3]), .QN (UNCONNECTED18));
  DFFSRHQX2 \LED_reg[15] (.RN (n_37), .SN (n_62), .CK (clk), .D
       (next_LED[15]), .Q (LED[15]));
  AO22X1 g5771__5107(.A0 (n_106), .A1 (n_109), .B0 (index[1]), .B1
       (n_111), .Y (n_112));
  MX2X1 g5772__6260(.A (n_109), .B (n_111), .S0 (index[0]), .Y (n_110));
  AO22X1 g5767__4319(.A0 (n_154), .A1 (n_104), .B0 (n_118), .B1
       (n_103), .Y (n_108));
  OR2XL g5786__8428(.A (n_106), .B (n_96), .Y (n_107));
  AO22X1 g5768__5526(.A0 (n_142), .A1 (n_104), .B0 (n_134), .B1
       (n_103), .Y (n_105));
  AO22X1 g5769__6783(.A0 (n_138), .A1 (n_239), .B0 (n_170), .B1
       (n_103), .Y (n_102));
  AO22X1 g5770__3680(.A0 (n_134), .A1 (n_104), .B0 (n_174), .B1
       (n_103), .Y (n_101));
  AND2X1 g5774__1617(.A (index[3]), .B (n_111), .Y (n_100));
  NAND2BXL g5776__2802(.AN (n_111), .B (n_79), .Y (n_99));
  OAI21XL g5777__1705(.A0 (index[2]), .A1 (n_9), .B0 (n_109), .Y
       (n_98));
  OR2X1 g5787__5122(.A (index[0]), .B (n_96), .Y (n_97));
  TLATNXL \next_LED_reg[15] (.GN (n_114), .D (n_80), .Q (next_LED[15]),
       .QN (UNCONNECTED19));
  AO22X1 g5760__8246(.A0 (n_166), .A1 (n_239), .B0 (n_154), .B1
       (n_103), .Y (n_95));
  AO22X1 g5756__7098(.A0 (n_130), .A1 (n_104), .B0 (n_126), .B1
       (n_103), .Y (n_94));
  AO22X1 g5757__6131(.A0 (n_177), .A1 (n_239), .B0 (n_162), .B1
       (n_103), .Y (n_93));
  AO22X1 g5758__1881(.A0 (n_158), .A1 (n_104), .B0 (n_166), .B1
       (n_103), .Y (n_92));
  AO22X1 g5759__5115(.A0 (n_162), .A1 (n_239), .B0 (n_130), .B1
       (n_103), .Y (n_91));
  OAI2BB1X1 g5755__7482(.A0N (n_158), .A1N (n_103), .B0 (n_84), .Y
       (n_90));
  AO22X1 g5762__4733(.A0 (n_146), .A1 (n_104), .B0 (n_138), .B1
       (n_103), .Y (n_89));
  AO22X1 g5763__6161(.A0 (n_126), .A1 (n_239), .B0 (n_122), .B1
       (n_103), .Y (n_88));
  AO22X1 g5764__9315(.A0 (n_118), .A1 (n_104), .B0 (n_150), .B1
       (n_103), .Y (n_87));
  AO22X1 g5765__9945(.A0 (n_122), .A1 (n_239), .B0 (n_146), .B1
       (n_103), .Y (n_86));
  AO22X1 g5766__2883(.A0 (n_150), .A1 (n_104), .B0 (n_142), .B1
       (n_103), .Y (n_85));
  TLATNXL \next_state_reg[0] (.GN (n_114), .D (n_84), .Q
       (next_state[0]), .QN (UNCONNECTED20));
  NAND2XL g5785__2346(.A (n_81), .B (n_70), .Y (n_83));
  NAND2XL g5788__1666(.A (n_81), .B (n_68), .Y (n_82));
  AND2X1 g5775__7410(.A (n_170), .B (n_239), .Y (n_80));
  NOR2XL g5778__6417(.A (n_79), .B (n_78), .Y (n_109));
  INVXL g5794(.A (n_81), .Y (n_96));
  AND2X1 g5779__5477(.A (state[1]), .B (n_78), .Y (n_111));
  AOI21XL g5789__2398(.A0 (n_106), .A1 (n_75), .B0 (n_74), .Y (n_77));
  AOI21XL g5790__5107(.A0 (index[0]), .A1 (n_75), .B0 (n_74), .Y
       (n_76));
  INVXL g5780(.A (n_239), .Y (n_84));
  OAI21X2 g5781__6260(.A0 (n_79), .A1 (n_58), .B0 (n_27), .Y (n_103));
  AND2XL g5798__4319(.A (n_204), .B (n_72), .Y (n_73));
  AOI2BB1XL g5792__8428(.A0N (n_70), .A1N (n_67), .B0 (n_74), .Y
       (n_71));
  AOI2BB1XL g5791__5526(.A0N (n_68), .A1N (n_213), .B0 (n_74), .Y
       (n_69));
  NOR2XL g5812__6783(.A (n_57), .B (n_72), .Y (n_81));
  NAND2XL g5802__3680(.A (n_226), .B (n_154), .Y (n_66));
  NAND2XL g5801__1617(.A (n_64), .B (n_130), .Y (n_65));
  NAND2XL g5795__2802(.A (n_64), .B (n_170), .Y (n_63));
  NAND2XL g5796__1705(.A (n_226), .B (n_174), .Y (n_62));
  NAND2XL g5797__5122(.A (n_64), .B (n_162), .Y (n_61));
  NAND2XL g5799__8246(.A (n_226), .B (n_166), .Y (n_60));
  NAND2XL g5800__7098(.A (n_64), .B (n_134), .Y (n_59));
  AND2X1 g5783__6131(.A (n_56), .B (n_58), .Y (n_78));
  OAI32X1 g5782__1881(.A0 (state[0]), .A1 (n_57), .A2 (n_39), .B0
       (n_79), .B1 (n_56), .Y (n_104));
  NAND2XL g5811__5115(.A (n_226), .B (n_177), .Y (n_55));
  NAND2XL g5804__7482(.A (n_64), .B (n_158), .Y (n_54));
  NAND2XL g5805__4733(.A (n_226), .B (n_118), .Y (n_53));
  NAND2XL g5806__6161(.A (n_64), .B (n_122), .Y (n_52));
  NAND2XL g5807__9315(.A (n_226), .B (n_150), .Y (n_51));
  NAND2XL g5808__9945(.A (n_64), .B (n_138), .Y (n_50));
  NAND2XL g5809__2883(.A (n_226), .B (n_146), .Y (n_49));
  NAND2XL g5810__2346(.A (n_226), .B (n_142), .Y (n_48));
  NAND2XL g5803__1666(.A (n_226), .B (n_126), .Y (n_47));
  OAI2BB1X1 g5830__7410(.A0N (n_57), .A1N (n_75), .B0 (rst_n), .Y
       (n_74));
  INVXL g5831(.A (n_64), .Y (n_72));
  OA21X1 g5817__6417(.A0 (n_166), .A1 (n_67), .B0 (n_204), .Y (n_46));
  OA21X1 g5829__5477(.A0 (n_170), .A1 (n_213), .B0 (rst_n), .Y (n_45));
  OA21X1 g5828__2398(.A0 (n_146), .A1 (n_67), .B0 (n_204), .Y (n_44));
  OA21X1 g5816__5107(.A0 (n_118), .A1 (n_213), .B0 (rst_n), .Y (n_43));
  OA21X1 g5813__6260(.A0 (n_158), .A1 (n_67), .B0 (n_204), .Y (n_42));
  OA21X1 g5814__4319(.A0 (n_150), .A1 (n_213), .B0 (rst_n), .Y (n_41));
  OA21X1 g5815__8428(.A0 (n_177), .A1 (n_67), .B0 (n_204), .Y (n_40));
  NAND2BXL g5784__5526(.AN (state[0]), .B (n_39), .Y (n_58));
  AND2X1 g5832__6783(.A (rst_n), .B (n_75), .Y (n_64));
  OA21X1 g5827__3680(.A0 (n_142), .A1 (n_213), .B0 (n_204), .Y (n_38));
  OA21X1 g5819__1617(.A0 (n_174), .A1 (n_67), .B0 (rst_n), .Y (n_37));
  OA21X1 g5820__2802(.A0 (n_154), .A1 (n_213), .B0 (n_204), .Y (n_36));
  OA21X1 g5821__1705(.A0 (n_126), .A1 (n_67), .B0 (rst_n), .Y (n_35));
  OA21X1 g5823__5122(.A0 (n_134), .A1 (n_213), .B0 (n_204), .Y (n_34));
  OA21X1 g5824__8246(.A0 (n_122), .A1 (n_67), .B0 (rst_n), .Y (n_33));
  OA21X1 g5825__7098(.A0 (n_138), .A1 (n_213), .B0 (n_204), .Y (n_32));
  OA21X1 g5826__6131(.A0 (n_162), .A1 (n_67), .B0 (rst_n), .Y (n_31));
  OA21X1 g5818__1881(.A0 (n_130), .A1 (n_67), .B0 (n_204), .Y (n_30));
  INVXL g5833(.A (n_213), .Y (n_75));
  OAI221X1 g5793__5115(.A0 (n_5), .A1 (n_16), .B0 (n_23), .B1 (n_17),
       .C0 (n_29), .Y (n_39));
  OR2X1 g5834__7482(.A (n_26), .B (n_28), .Y (n_67));
  NAND4XL g5822__4733(.A (n_154), .B (n_126), .C (n_21), .D (n_24), .Y
       (n_29));
  OAI2BB1X1 g5835__6161(.A0N (state[1]), .A1N (n_22), .B0 (flick), .Y
       (n_28));
  NAND3BXL g5837__9315(.AN (n_57), .B (state[0]), .C (n_25), .Y (n_27));
  OR2X1 g5838__9945(.A (n_26), .B (n_25), .Y (n_56));
  OAI31X1 g5836__2883(.A0 (n_148), .A1 (n_152), .A2 (n_18), .B0 (n_23),
       .Y (n_24));
  OAI211X1 g5840__2346(.A0 (n_21), .A1 (n_20), .B0 (n_11), .C0 (n_19),
       .Y (n_22));
  OAI21XL g5839__1666(.A0 (n_20), .A1 (n_15), .B0 (n_19), .Y (n_25));
  OAI211X1 g5841__7410(.A0 (index[1]), .A1 (n_12), .B0 (n_122), .C0
       (n_118), .Y (n_18));
  NOR4BBX1 g5842__6417(.AN (n_17), .BN (n_16), .C (n_126), .D (n_154),
       .Y (n_19));
  XNOR2X1 g5847__5477(.A (index[3]), .B (n_13), .Y (n_68));
  OR3X1 g5848__2398(.A (index[3]), .B (n_57), .C (n_14), .Y (n_79));
  NOR2BX1 g5849__5107(.AN (n_106), .B (index[2]), .Y (n_15));
  NAND2BXL g5851__6260(.AN (n_14), .B (n_13), .Y (n_70));
  NOR2BX1 g5843__4319(.AN (n_170), .B (n_8), .Y (n_12));
  NOR4X1 g5844__8428(.A (n_142), .B (n_138), .C (n_134), .D (n_4), .Y
       (n_16));
  NOR4X1 g5845__5526(.A (n_162), .B (n_130), .C (n_158), .D (n_6), .Y
       (n_20));
  NOR2BX1 g5846__6783(.AN (n_130), .B (n_7), .Y (n_21));
  NAND3BXL g5850__3680(.AN (n_23), .B (index[0]), .C (n_0), .Y (n_11));
  NOR2BX1 g5857__1617(.AN (index[2]), .B (n_10), .Y (n_14));
  NAND2BXL g5855__2802(.AN (index[2]), .B (n_10), .Y (n_13));
  NOR2XL g5856__1705(.A (n_9), .B (n_10), .Y (n_106));
  AND3XL g5858__5122(.A (n_1), .B (n_26), .C (n_57), .Y (n_114));
  NAND4XL g5853__8246(.A (n_138), .B (n_134), .C (n_174), .D (n_142),
       .Y (n_8));
  NAND4XL g5852__7098(.A (n_162), .B (n_166), .C (n_158), .D (n_177),
       .Y (n_7));
  NOR4X1 g5854__6131(.A (n_146), .B (n_118), .C (n_122), .D (n_150), .Y
       (n_17));
  OR2X1 g5859__1881(.A (n_177), .B (n_166), .Y (n_6));
  NOR2XL g5862__5115(.A (index[1]), .B (index[2]), .Y (n_5));
  NOR2XL g5861__7482(.A (index[1]), .B (index[0]), .Y (n_10));
  OR2X1 g5863__4733(.A (n_170), .B (n_174), .Y (n_4));
  AND2X1 g5864__6161(.A (index[1]), .B (index[0]), .Y (n_9));
  NAND2BXL g5860__9315(.AN (index[1]), .B (index[2]), .Y (n_23));
  INVXL g5870(.A (rst_n), .Y (n_1));
  BUFX2 fopt5933(.A (LED[15]), .Y (n_174));
  BUFX2 fopt5935(.A (LED[0]), .Y (n_177));
  BUFX2 fopt5937(.A (LED[1]), .Y (n_158));
  BUFX2 fopt5939(.A (LED[2]), .Y (n_162));
  BUFX2 fopt5941(.A (LED[3]), .Y (n_166));
  BUFX2 fopt5943(.A (LED[4]), .Y (n_130));
  BUFX2 fopt5945(.A (LED[5]), .Y (n_154));
  BUFX2 fopt5947(.A (LED[6]), .Y (n_126));
  BUFX2 fopt5949(.A (LED[7]), .Y (n_118));
  BUFX2 fopt5951(.A (LED[8]), .Y (n_122));
  BUFX2 fopt5953(.A (LED[9]), .Y (n_150));
  BUFX2 fopt5955(.A (LED[10]), .Y (n_146));
  BUFX2 fopt5957(.A (LED[11]), .Y (n_142));
  BUFX2 fopt5959(.A (LED[12]), .Y (n_138));
  BUFX2 fopt5961(.A (LED[13]), .Y (n_134));
  BUFX2 fopt5963(.A (LED[14]), .Y (n_170));
  BUFX2 drc_buf_sp5987(.A (rst_n), .Y (n_204));
  BUFX2 drc_buf_sp5995(.A (n_67), .Y (n_213));
  BUFX2 drc_buf_sp6007(.A (n_64), .Y (n_226));
  BUFX2 drc_buf_sp6019(.A (n_104), .Y (n_239));
  DFFRX1 \state_reg[0] (.RN (n_73), .CK (clk), .D (next_state[0]), .Q
       (state[0]), .QN (n_26));
  DFFSRX1 \index_reg[3] (.RN (n_69), .SN (n_82), .CK (clk), .D
       (next_index[3]), .Q (index[3]), .QN (n_0));
  DFFSRX1 \state_reg[1] (.RN (rst_n), .SN (n_72), .CK (clk), .D
       (next_state[1]), .Q (state[1]), .QN (n_57));
  INVX1 fopt6032(.A (n_146), .Y (n_148));
  INVX1 fopt6034(.A (n_150), .Y (n_152));
endmodule

