
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  4 2020 22:44:58 +07 (Aug  4 2020 15:44:58 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(clk, rst_n, flick, LED);
  input clk, rst_n, flick;
  output [15:0] LED;
  wire clk, rst_n, flick;
  wire [15:0] LED;
  wire [3:0] next_index;
  wire [3:0] index;
  wire [15:0] next_LED;
  wire [1:0] next_state;
  wire [1:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, n_0, n_1;
  wire n_2, n_3, n_4, n_6, n_7, n_8, n_11, n_12;
  wire n_13, n_14, n_15, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_26, n_27, n_28, n_29, n_30;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_138, n_139, n_140;
  DFFSRHQX4 \index_reg[1] (.RN (n_59), .SN (n_65), .CK (clk), .D
       (next_index[1]), .Q (index[1]));
  SDFFRHQX4 \LED_reg[9] (.RN (n_109), .CK (clk), .D (next_LED[9]), .SI
       (LED[9]), .SE (n_108), .Q (LED[9]));
  SDFFRHQX4 \LED_reg[2] (.RN (n_109), .CK (clk), .D (next_LED[2]), .SI
       (LED[2]), .SE (n_108), .Q (LED[2]));
  SDFFRHQX4 \LED_reg[13] (.RN (n_109), .CK (clk), .D (next_LED[13]),
       .SI (LED[13]), .SE (n_108), .Q (LED[13]));
  SDFFRHQX4 \LED_reg[4] (.RN (n_109), .CK (clk), .D (next_LED[4]), .SI
       (LED[4]), .SE (n_108), .Q (LED[4]));
  SDFFRHQX4 \LED_reg[3] (.RN (n_109), .CK (clk), .D (next_LED[3]), .SI
       (LED[3]), .SE (n_108), .Q (LED[3]));
  SDFFRHQX4 \LED_reg[1] (.RN (n_109), .CK (clk), .D (next_LED[1]), .SI
       (LED[1]), .SE (n_108), .Q (LED[1]));
  SDFFRHQX4 \LED_reg[14] (.RN (n_109), .CK (clk), .D (next_LED[14]),
       .SI (LED[14]), .SE (n_108), .Q (LED[14]));
  SDFFRHQX4 \LED_reg[11] (.RN (n_109), .CK (clk), .D (next_LED[11]),
       .SI (LED[11]), .SE (n_108), .Q (LED[11]));
  SDFFRHQX4 \LED_reg[7] (.RN (n_109), .CK (clk), .D (next_LED[7]), .SI
       (LED[7]), .SE (n_108), .Q (LED[7]));
  SDFFRHQX4 \LED_reg[8] (.RN (n_109), .CK (clk), .D (next_LED[8]), .SI
       (LED[8]), .SE (n_108), .Q (LED[8]));
  SDFFRHQX4 \LED_reg[5] (.RN (n_109), .CK (clk), .D (next_LED[5]), .SI
       (LED[5]), .SE (n_108), .Q (LED[5]));
  SDFFRHQX4 \LED_reg[10] (.RN (n_109), .CK (clk), .D (next_LED[10]),
       .SI (LED[10]), .SE (n_108), .Q (LED[10]));
  SDFFRHQX4 \LED_reg[12] (.RN (n_109), .CK (clk), .D (next_LED[12]),
       .SI (LED[12]), .SE (n_108), .Q (LED[12]));
  SDFFRHQX4 \LED_reg[6] (.RN (n_109), .CK (clk), .D (next_LED[6]), .SI
       (LED[6]), .SE (n_108), .Q (LED[6]));
  SDFFRHQX4 \LED_reg[0] (.RN (n_109), .CK (clk), .D (next_LED[0]), .SI
       (LED[0]), .SE (n_108), .Q (LED[0]));
  TLATNXL \next_index_reg[1] (.GN (n_107), .D (n_106), .Q
       (next_index[1]), .QN (UNCONNECTED));
  TLATNXL \next_index_reg[2] (.GN (n_107), .D (n_105), .Q
       (next_index[2]), .QN (UNCONNECTED0));
  SDFFRHQX4 \LED_reg[15] (.RN (n_109), .CK (clk), .D (next_LED[15]),
       .SI (LED[15]), .SE (n_108), .Q (LED[15]));
  OAI32X1 g5169__2398(.A0 (index[1]), .A1 (n_75), .A2 (n_81), .B0
       (n_11), .B1 (n_93), .Y (n_106));
  AO22X1 g5170__5107(.A0 (n_23), .A1 (n_103), .B0 (index[2]), .B1
       (n_94), .Y (n_105));
  TLATNXL \next_index_reg[0] (.GN (n_107), .D (n_104), .Q
       (next_index[0]), .QN (UNCONNECTED1));
  DFFSRHQX2 \index_reg[3] (.RN (n_54), .SN (n_62), .CK (clk), .D
       (next_index[3]), .Q (index[3]));
  TLATNXL \next_LED_reg[6] (.GN (n_107), .D (n_91), .Q (next_LED[6]),
       .QN (UNCONNECTED2));
  TLATNXL \next_LED_reg[1] (.GN (n_107), .D (n_85), .Q (next_LED[1]),
       .QN (UNCONNECTED3));
  TLATNXL \next_LED_reg[2] (.GN (n_107), .D (n_90), .Q (next_LED[2]),
       .QN (UNCONNECTED4));
  TLATNXL \next_LED_reg[3] (.GN (n_107), .D (n_87), .Q (next_LED[3]),
       .QN (UNCONNECTED5));
  TLATNXL \next_LED_reg[14] (.GN (n_107), .D (n_102), .Q
       (next_LED[14]), .QN (UNCONNECTED6));
  TLATNXL \next_LED_reg[5] (.GN (n_107), .D (n_86), .Q (next_LED[5]),
       .QN (UNCONNECTED7));
  TLATNXL \next_LED_reg[4] (.GN (n_107), .D (n_92), .Q (next_LED[4]),
       .QN (UNCONNECTED8));
  TLATNXL \next_LED_reg[8] (.GN (n_107), .D (n_83), .Q (next_LED[8]),
       .QN (UNCONNECTED9));
  TLATNXL \next_LED_reg[9] (.GN (n_107), .D (n_82), .Q (next_LED[9]),
       .QN (UNCONNECTED10));
  TLATNXL \next_LED_reg[10] (.GN (n_107), .D (n_96), .Q (next_LED[10]),
       .QN (UNCONNECTED11));
  TLATNXL \next_LED_reg[11] (.GN (n_107), .D (n_101), .Q
       (next_LED[11]), .QN (UNCONNECTED12));
  TLATNXL \next_LED_reg[12] (.GN (n_107), .D (n_98), .Q (next_LED[12]),
       .QN (UNCONNECTED13));
  TLATNXL \next_LED_reg[13] (.GN (n_107), .D (n_97), .Q (next_LED[13]),
       .QN (UNCONNECTED14));
  TLATNXL \next_LED_reg[7] (.GN (n_107), .D (n_84), .Q (next_LED[7]),
       .QN (UNCONNECTED15));
  MX2X1 g5179__6260(.A (n_103), .B (n_77), .S0 (index[0]), .Y (n_104));
  TLATNXL \next_index_reg[3] (.GN (n_107), .D (n_78), .Q
       (next_index[3]), .QN (UNCONNECTED16));
  TLATNXL \next_state_reg[1] (.GN (n_107), .D (n_76), .Q
       (next_state[1]), .QN (UNCONNECTED17));
  TLATNXL \next_LED_reg[0] (.GN (n_107), .D (n_80), .Q (next_LED[0]),
       .QN (UNCONNECTED18));
  AO22X1 g5208__4319(.A0 (LED[15]), .A1 (n_100), .B0 (LED[13]), .B1
       (n_99), .Y (n_102));
  AO22X1 g5205__8428(.A0 (LED[12]), .A1 (n_100), .B0 (LED[10]), .B1
       (n_99), .Y (n_101));
  AO22X1 g5206__5526(.A0 (LED[13]), .A1 (n_100), .B0 (LED[11]), .B1
       (n_99), .Y (n_98));
  AO22X1 g5207__6783(.A0 (LED[14]), .A1 (n_100), .B0 (LED[12]), .B1
       (n_99), .Y (n_97));
  AO22X1 g5204__3680(.A0 (LED[11]), .A1 (n_100), .B0 (LED[9]), .B1
       (n_99), .Y (n_96));
  INVXL g5188(.A (n_93), .Y (n_94));
  AO22X1 g5189__1617(.A0 (LED[5]), .A1 (n_89), .B0 (LED[3]), .B1
       (n_88), .Y (n_92));
  TLATNXL \next_LED_reg[15] (.GN (n_107), .D (n_74), .Q (next_LED[15]),
       .QN (UNCONNECTED19));
  AO22X1 g5200__2802(.A0 (LED[7]), .A1 (n_100), .B0 (LED[5]), .B1
       (n_99), .Y (n_91));
  AO22X1 g5195__1705(.A0 (LED[3]), .A1 (n_89), .B0 (LED[1]), .B1
       (n_88), .Y (n_90));
  AO22X1 g5196__5122(.A0 (LED[4]), .A1 (n_89), .B0 (LED[2]), .B1
       (n_88), .Y (n_87));
  AO22X1 g5199__8246(.A0 (LED[6]), .A1 (n_89), .B0 (LED[4]), .B1
       (n_88), .Y (n_86));
  AO22X1 g5194__7098(.A0 (LED[2]), .A1 (n_89), .B0 (LED[0]), .B1
       (n_88), .Y (n_85));
  AO22X1 g5201__6131(.A0 (LED[8]), .A1 (n_100), .B0 (LED[6]), .B1
       (n_99), .Y (n_84));
  AO22X1 g5202__1881(.A0 (LED[9]), .A1 (n_100), .B0 (LED[7]), .B1
       (n_99), .Y (n_83));
  AO22X1 g5203__5115(.A0 (LED[10]), .A1 (n_100), .B0 (LED[8]), .B1
       (n_99), .Y (n_82));
  TLATNXL \next_state_reg[0] (.GN (n_107), .D (n_79), .Q
       (next_state[0]), .QN (UNCONNECTED20));
  INVXL g5211(.A (n_103), .Y (n_81));
  OAI2BB1X1 g5213__7482(.A0N (LED[1]), .A1N (n_50), .B0 (n_79), .Y
       (n_80));
  AND2X1 g5191__4733(.A (index[3]), .B (n_77), .Y (n_78));
  NAND2BXL g5192__6161(.AN (n_77), .B (n_73), .Y (n_76));
  AOI21XL g5197__9315(.A0 (n_75), .A1 (n_67), .B0 (n_77), .Y (n_93));
  AND2X1 g5212__9945(.A (LED[14]), .B (n_99), .Y (n_74));
  OAI32X1 g5214__2883(.A0 (n_68), .A1 (n_73), .A2 (n_46), .B0
       (state[0]), .B1 (n_72), .Y (n_103));
  NAND2XL g5210__2346(.A (n_70), .B (n_71), .Y (n_77));
  NAND2XL g5216__1666(.A (n_72), .B (n_71), .Y (n_89));
  INVXL g5218(.A (n_88), .Y (n_79));
  OAI2BB1X1 g5220__7410(.A0N (state[0]), .A1N (state[1]), .B0 (n_72),
       .Y (n_100));
  INVXL g5215(.A (n_70), .Y (n_99));
  AOI211X1 g5219__6417(.A0 (state[0]), .A1 (n_45), .B0 (n_17), .C0
       (n_69), .Y (n_88));
  NAND3BXL g5217__5477(.AN (n_69), .B (n_68), .C (state[1]), .Y (n_70));
  NAND2XL g5221__2398(.A (n_69), .B (n_67), .Y (n_72));
  OAI221X1 g5222__5107(.A0 (n_3), .A1 (n_41), .B0 (n_47), .B1 (n_42),
       .C0 (n_138), .Y (n_69));
  OR2XL g5226__6260(.A (n_51), .B (n_64), .Y (n_66));
  OR2XL g5227__4319(.A (n_58), .B (n_64), .Y (n_65));
  OR2XL g5228__8428(.A (index[0]), .B (n_64), .Y (n_63));
  OR2XL g5229__5526(.A (n_53), .B (n_64), .Y (n_62));
  OAI21XL g5230__3680(.A0 (n_27), .A1 (n_57), .B0 (rst_n), .Y (n_60));
  AOI21XL g5231__1617(.A0 (n_58), .A1 (n_57), .B0 (n_55), .Y (n_59));
  AOI21XL g5232__2802(.A0 (index[0]), .A1 (n_57), .B0 (n_55), .Y
       (n_56));
  AOI21XL g5233__1705(.A0 (n_53), .A1 (n_57), .B0 (n_55), .Y (n_54));
  AOI21XL g5234__5122(.A0 (n_51), .A1 (n_57), .B0 (n_55), .Y (n_52));
  NAND3XL g5238__8246(.A (rst_n), .B (state[1]), .C (n_57), .Y (n_64));
  NAND2XL g5224__7098(.A (n_71), .B (n_73), .Y (n_50));
  NOR2XL g5237__6131(.A (n_33), .B (n_57), .Y (n_49));
  OAI31X1 g5225__1881(.A0 (n_0), .A1 (n_1), .A2 (n_43), .B0 (n_47), .Y
       (n_48));
  NAND3XL g5235__5115(.A (state[1]), .B (state[0]), .C (n_46), .Y
       (n_71));
  BUFX2 g5239(.A (n_108), .Y (n_57));
  NAND2BXL g5236__7482(.AN (n_46), .B (n_34), .Y (n_45));
  INVX12 g5240(.A (n_44), .Y (n_108));
  OA21X4 g5241__4733(.A0 (n_40), .A1 (n_39), .B0 (n_38), .Y (n_44));
  OAI211X1 g5242__6161(.A0 (index[1]), .A1 (n_37), .B0 (LED[8]), .C0
       (LED[7]), .Y (n_43));
  NAND4X1 g5243__9315(.A (n_20), .B (n_42), .C (n_41), .D (n_36), .Y
       (n_46));
  OAI21X2 g5244__9945(.A0 (n_35), .A1 (n_30), .B0 (n_139), .Y (n_40));
  INVXL g5245(.A (n_73), .Y (n_67));
  NAND3BX4 g5250__2883(.AN (n_21), .B (n_41), .C (flick), .Y (n_39));
  NAND2XL g5247__2346(.A (n_109), .B (n_38), .Y (n_55));
  NOR2BX1 g5246__1666(.AN (LED[14]), .B (n_28), .Y (n_37));
  AO21X1 g5249__7410(.A0 (n_19), .A1 (n_58), .B0 (n_35), .Y (n_36));
  NAND2XL g5248__6417(.A (state[1]), .B (n_34), .Y (n_73));
  XNOR2X1 g5251__5477(.A (n_29), .B (index[3]), .Y (n_53));
  INVXL g5252(.A (n_33), .Y (n_109));
  NOR2X4 g5259__5107(.A (n_8), .B (n_140), .Y (n_30));
  NOR2XL g5254__6260(.A (n_26), .B (n_29), .Y (n_51));
  CLKAND2X6 g5261__4319(.A (n_2), .B (n_22), .Y (n_41));
  NAND4XL g5258__8428(.A (LED[13]), .B (LED[12]), .C (LED[15]), .D
       (LED[11]), .Y (n_28));
  NAND2BXL g5256__5526(.AN (n_27), .B (rst_n), .Y (n_33));
  NOR2XL g5255__6783(.A (index[3]), .B (n_26), .Y (n_34));
  CLKAND2X3 g5260__3680(.A (n_6), .B (n_14), .Y (n_35));
  NAND2X2 g5264__1617(.A (n_12), .B (flick), .Y (n_38));
  INVXL g5268(.A (n_24), .Y (n_42));
  NOR2XL g5267__1705(.A (n_23), .B (n_18), .Y (n_58));
  NOR3X4 g5263__5122(.A (LED[15]), .B (LED[12]), .C (LED[11]), .Y
       (n_22));
  NOR2XL g5265__8246(.A (n_19), .B (n_18), .Y (n_26));
  AND3XL g5272__7098(.A (n_68), .B (n_17), .C (flick), .Y (n_27));
  NAND2X4 g5273__1881(.A (n_7), .B (n_4), .Y (n_24));
  AND2X1 g5266__5115(.A (n_19), .B (n_18), .Y (n_29));
  INVXL g5281(.A (n_15), .Y (n_47));
  NOR3X4 g5271__7482(.A (LED[1]), .B (LED[4]), .C (LED[0]), .Y (n_14));
  NOR2X4 g5276__4733(.A (index[3]), .B (n_75), .Y (n_13));
  NOR2X4 g5288__6161(.A (index[1]), .B (n_19), .Y (n_15));
  NOR2XL g5286__9315(.A (n_11), .B (n_75), .Y (n_23));
  NOR3X1 g5274__9945(.A (state[0]), .B (state[1]), .C (rst_n), .Y
       (n_107));
  NAND2X2 g5279__2346(.A (LED[1]), .B (LED[2]), .Y (n_8));
  NOR2X4 g5278__1666(.A (LED[10]), .B (LED[8]), .Y (n_7));
  NOR2X2 g5280__7410(.A (LED[3]), .B (LED[2]), .Y (n_6));
  NOR2X4 g5282__6417(.A (LED[9]), .B (LED[7]), .Y (n_4));
  NOR2XL g5283__5477(.A (index[1]), .B (index[2]), .Y (n_3));
  NOR2X2 g5277__2398(.A (LED[14]), .B (LED[13]), .Y (n_2));
  NOR2X4 g5285__5107(.A (LED[6]), .B (LED[5]), .Y (n_20));
  NOR2XL g5287__6260(.A (index[1]), .B (index[0]), .Y (n_18));
  INVXL g5290(.A (LED[9]), .Y (n_1));
  INVXL g5289(.A (LED[10]), .Y (n_0));
  INVXL g5291(.A (index[1]), .Y (n_11));
  NOR2X2 g5344__4319(.A (state[1]), .B (n_68), .Y (n_12));
  NAND2X4 g5346__8428(.A (state[0]), .B (n_20), .Y (n_21));
  DFFSRX2 \state_reg[1] (.RN (rst_n), .SN (n_60), .CK (clk), .D
       (next_state[1]), .Q (state[1]), .QN (n_17));
  DFFRX2 \state_reg[0] (.RN (n_49), .CK (clk), .D (next_state[0]), .Q
       (state[0]), .QN (n_68));
  NAND4XL g2(.A (n_30), .B (LED[6]), .C (LED[5]), .D (n_48), .Y
       (n_138));
  AOI21X4 g5374(.A0 (n_13), .A1 (n_15), .B0 (n_24), .Y (n_139));
  NAND3X4 g5375(.A (LED[3]), .B (LED[4]), .C (LED[0]), .Y (n_140));
  DFFSRX4 \index_reg[2] (.RN (n_52), .SN (n_66), .CK (clk), .D
       (next_index[2]), .Q (index[2]), .QN (n_19));
  DFFSRX4 \index_reg[0] (.RN (n_56), .SN (n_63), .CK (clk), .D
       (next_index[0]), .Q (index[0]), .QN (n_75));
endmodule

